CREATE TABLE TB_USER (
    USER_ID        BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 ID',
    USERNAME       VARCHAR(50) NOT NULL UNIQUE COMMENT '로그인 아이디',
    PASSWORD       VARCHAR(255) NOT NULL COMMENT '비밀번호(암호화)',
    NAME           VARCHAR(100) COMMENT '이름',
    EMAIL          VARCHAR(100) COMMENT '이메일',
    PHONE          VARCHAR(20) COMMENT '전화번호',
    STATUS         VARCHAR(10) DEFAULT 'ACTIVE' COMMENT '계정 상태(ACTIVE, INACTIVE, LOCKED 등)',
    LOGIN_FAIL_CNT INT DEFAULT 0 COMMENT '로그인 실패 횟수',
    LAST_LOGIN_DT  DATETIME COMMENT '마지막 로그인 일시',
    INIT_PW_YN        CHAR(1) DEFAULT 'Y' COMMENT '초기 비밀번호 여부 (Y: 초기비밀번호, N: 변경완료)',
   	LAST_UPDATE_PASS DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '마지막 비밀번호 변경 일시',
    REG_DT         DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_DT         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시'
) COMMENT='사용자 기본 정보';


CREATE TABLE TB_ROLE (
    ROLE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '권한 ID',
    ROLE_CODE VARCHAR(50) NOT NULL UNIQUE COMMENT '권한 코드 (ex: ROLE_ADMIN, ROLE_USER)',
    ROLE_NM   VARCHAR(100) COMMENT '권한명',
    ROLE_DC   VARCHAR(255) COMMENT '권한 설명',
    USE_AT    CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    REG_DT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPD_DT    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='권한 정보';


CREATE TABLE TB_USER_ROLE (
    USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자권한ID',
    USER_ID      BIGINT NOT NULL COMMENT '사용자 ID',
    ROLE_ID      BIGINT NOT NULL COMMENT '권한 ID',
    GRANT_DT     DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '권한 부여 일시',
    CONSTRAINT FK_USERROLE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    CONSTRAINT FK_USERROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID)
) COMMENT='사용자-권한 매핑';


CREATE TABLE TB_LOGIN_HISTORY (
    LOGIN_HIS_ID  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '로그인 이력 ID',
    USER_ID       BIGINT COMMENT '사용자 ID',
    USERNAME      VARCHAR(50) COMMENT '로그인 시도 아이디',
    DOMAIN_SE     VARCHAR(50) COMMENT '로그인 도메인 구분 (PORTAL, CHAT, SHOP 등)',
    LOGIN_IP      VARCHAR(45) COMMENT '접속 IP',
    LOGIN_RESULT  VARCHAR(10) COMMENT '결과(SUCCESS, FAIL)',
    FAIL_REASON   VARCHAR(255) COMMENT '실패 사유',
    USER_AGENT    VARCHAR(255) COMMENT '브라우저/디바이스 정보',
    LOGIN_DT      DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '로그인 일시',
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
) COMMENT='로그인 이력';


CREATE TABLE TB_USER_REFRESH_TOKEN (
    USERNAME       VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '사용자 ID',
    REFRESH_TOKEN  VARCHAR(512) NOT NULL COMMENT '리프레시 토큰(JWT 또는 난수)',
    EXPIRES_AT     DATETIME NOT NULL COMMENT '리프레시 토큰 만료 일시',
    REVOKED_YN     CHAR(1) DEFAULT 'N' COMMENT '토큰 폐기 여부 (Y: 폐기, N: 사용중)',
    REG_DT         DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_DT         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT FK_USER_REFRESH_USER FOREIGN KEY (USERNAME) REFERENCES TB_USER(USERNAME)
) COMMENT='사용자 리프레시 토큰 관리';
